# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '分组',
                'verbose_name_plural': '分组',
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlboard.Group', verbose_name='分组')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URL',
            },
        ),
    ]
