# Generated by Django 2.0 on 2018-02-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rws', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tdatareportconfig',
            options={'managed': True, 'verbose_name': 'rws-定时邮件发送任务', 'verbose_name_plural': 'rws-定时邮件发送任务'},
        ),
    ]
