# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('content', models.CharField(max_length=200, verbose_name='执行查询内容：表，视图，存储过程')),
                ('para', models.CharField(blank=True, max_length=200, verbose_name='参数')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('limit', models.IntegerField(default=10, verbose_name='页面展示数量')),
                ('output', models.CharField(default='', max_length=200, verbose_name='输出字段')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('dataase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protal.Database')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('code', models.CharField(max_length=200, verbose_name='方法类型')),
                ('desc', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
        ),
        migrations.AddField(
            model_name='function',
            name='funcode',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='protal.FunctionCode', verbose_name='方法类型'),
        ),
        migrations.AddField(
            model_name='database',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protal.DatabaseType', verbose_name='类型'),
        ),
    ]
